name: React app deployment

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

env:
  CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
  CI_COMMIT_AUTHOR: Continuous Integration
  CI_COMMIT_EMAIL: "username@users.noreply.github.com"

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch News
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd news_fetcher
          pip install -r requirements.txt
          python3 crawl_data.py

      - name: Build React App
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./dist

      - name: GIT commit and push all changed files
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
